name: IO-Accounts
main: org.iocraft.accounts.Main
version: 1.0.0
description: IO-Accountsis a plugin designed for a simple night vision ability and permission.
author: ioCraft.org Team
website: https://www.iocraft.org

commands:
   accounts:
      description: Includes info and reloads.
      usage: /accounts <help, reload>
   nv:
      description: Toggles night vision.
      usage: /nv
      permission: io.accounts.nv
      permission-message: You don't have <permission>

permissions:
    io.accounts.*:
        description: Gives access to all IO-Accountscommands.
        children:
            io.accounts.player.*: true
            io.accounts.reload: true
    io.accounts.player.*:
        description: Gives access to all player commands.
        children:
            io.accounts.help: true
            io.accounts.nv: true
            io.accounts.reload: false
    io.accounts.help:
        description: Show a list of commands for IO-Accounts.
        default: true
    io.accounts.nv:
        description: Toggles night vision.
        default: true
    io.accounts.reload:
        description: Reload the configuration.
        default: op